# Lecture 10
## Working with arrays

### Creating Arrays from Scratch

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy.
Here are several examples:

In [1]:
import numpy as np

In [13]:
# Create a length-10 integer array filled with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros(10, dtype = 'int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.zeros(10, dtype = int16)

NameError: name 'int16' is not defined

In [18]:
np.zeros(10, dtype = np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [3]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype = 'float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
np.full((3, 5), 3.14, dtype = np.int16)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [5]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.17009874, 0.75015877, 0.78847256],
       [0.77589528, 0.17673443, 0.93956522],
       [0.29778516, 0.62123922, 0.75549086]])

In [8]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[ 0.12613332, -0.368738  ,  0.54012315],
       [-2.91748571, -0.49039859,  0.60146947],
       [ 0.79197234,  1.53652123,  0.0490612 ]])

In [23]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3,3))

array([[5, 0, 0],
       [4, 2, 1],
       [4, 3, 3]])

In [31]:
np.random.seed(0)
np.random.randint(0, 10, (3,3))

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [32]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

`diag` extracts a diagonal or constructs a diagonal array.

In [34]:
y = np.array([1, 2, 3])
y

array([1, 2, 3])

In [35]:
np.diag(y)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [36]:
d = np.arange(9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.diag(d)

array([0, 4, 8])

Create an array using repeating list

In [38]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

The same with `np.tile`

In [39]:
np.tile([1, 2, 3], 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Repeat elements of an array using `repeat`.

In [40]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Array Indexing: Accessing Single Elements
If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [47]:
x1 = np.arange(1,10)

In [48]:
x1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x1[1]

2

In [50]:
x1[4] = -12

To index from the end of the array, you can use negative indices:

In [52]:
x1[-2]

8

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [57]:
x2 = x1.reshape((3,3))
x2

array([[  1,   2,   3],
       [  4, -12,   6],
       [  7,   8,   9]])

In [58]:
x2[2, -1]

9

Values can also be modified using any of the above index notation:

In [59]:
x2[0, 0] = 12
x2

array([[ 12,   2,   3],
       [  4, -12,   6],
       [  7,   8,   9]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!

In [60]:
# this will be truncated!
x2[0, 0] = 3.9
x2

array([[  3,   2,   3],
       [  4, -12,   6],
       [  7,   8,   9]])

In [61]:
x2[0, 0] = 'a'

ValueError: invalid literal for int() with base 10: 'a'

## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

### One-dimensional subarrays

In [68]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
# first five elements
x[:5]

array([0, 1, 2, 3, 4])

In [70]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [71]:
# middle sub-array
x[4:7]

array([4, 5, 6])

In [72]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [73]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

A potentially confusing case is when the ``step`` value is negative.
In this case, the defaults for ``start`` and ``stop`` are swapped.
This becomes a convenient way to reverse an array:

In [74]:
# all elements, reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [75]:
# reversed every other from index 5
x[5::-2]

array([5, 3, 1])

### Multi-dimensional subarrays

Multi-dimensional slices work in the same way, with multiple slices separated by commas.
For example:

Let's another look at a multidimensional array.

In [86]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: `array[row, column]`

In [87]:
r[2, 2]

14


And use : to select a range of rows or columns

In [86]:
r[3, 3:6]

array([21, 22, 23])

In [ ]:
# all rows, every other column
x2[:, ::2] # or x2[:3, ::2]

Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [ ]:
r[:2, :-1]

This is a slice of the last row, and only every other element.

In [87]:
r[-1, ::2]

array([30, 32, 34])

Subarray dimensions can even be reversed together:

In [84]:
x2[::-1, ::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. 

In [88]:
r > 30

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True]])

In [89]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [90]:
np.where(r < 10, 0, r)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [90]:
np.where?

In [92]:
np.where([[True, False], [False, True]],
          [[1, 2], [3, 4]],
          [[9, 8], [7, 6]])

array([[1, 8],
       [7, 4]])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [91]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

#### Accessing array rows and columns

One commonly needed routine is accessing of single rows or columns of an array.
This can be done by combining indexing and slicing, using an empty slice marked by a single colon (``:``):

In [93]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
x2.shape

(3, 4)

In [95]:
x2[:, 0]  # first column of x2

array([0, 4, 8])

In [97]:
x2[:, 0].shape

(3,)

In [99]:
x2[0, :]  # first row of x2

array([0, 1, 2, 3])

In [101]:
x2[0, :].shape

(4,)

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [102]:
x2[0]  # equivalent to x2[0, :]

array([0, 1, 2, 3])

### Subarrays as no-copy views

One important–and extremely useful–thing to know about array slices is that they return *views* rather than *copies* of the array data.
This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies.
Consider our two-dimensional array from before:

In [104]:
x2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Let's extract a $2 \times 2$ subarray from this:

In [105]:
x2_sub = x2[:2, :2]
x2_sub

array([[0, 1],
       [4, 5]])

Now if we modify this subarray, we'll see that the original array is changed! Observe:

In [106]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  1],
       [ 4,  5]])

In [107]:
x2

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
a = a=[[1, 2, 3],[4, 5, 6],[7, 8, 9]]
b = a[:2]
b[1] = 10
b

[[1, 2, 3], 10]

In [134]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.

## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [136]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [135]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [137]:
r is r2

False

Set this slice's values to zero (`[:]` selects the entire array)

In [138]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`r` has also been changed!

In [139]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [105]:
id(r)

106554992

In [106]:
id(r2)

107409456

In [107]:
id(r) == id(r2)

False

To avoid this, use `r.copy` to create a copy that will not affect the original array

In [140]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Now when r_copy is modified, r will not be changed.

In [141]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays.
The most flexible way of doing this is with the ``reshape`` method.
For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:

In [142]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 
Where possible, the ``reshape`` method will use a no-copy view of the initial array, but with non-contiguous memory buffers this is not always the case.

Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix.
This can be done with the ``reshape`` method, or more easily done by making use of the ``newaxis`` keyword within a slice operation:

In [148]:
x = np.array([1, 2, 3])
print(x.shape)
# row to vector via reshape
xx = x.reshape((1, 3))
print(xx.shape)

(3,)
(1, 3)


In [149]:
# row vector via newaxis
y = x[np.newaxis, :]
print(y.shape)

(1, 3)


In [111]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [112]:
# column vector via newaxis
y = x[:, np.newaxis]

In [113]:
y.shape

(3, 1)

`reshape` returns an array with the same data with a new shape.

In [114]:
n=np.arange(15)
nn = n.reshape(3, 5) # reshape array to be 3x5
nn

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [115]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

`linspace` returns evenly spaced numbers over a specified interval.

In [116]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

`resize` changes the shape and size of array in-place.


In [117]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

Difference between `reshape` and `resize`:<br>
Both reshape and resize change the shape of the numpy array; the difference is that using `resize` will affect the original array while using `reshape` create a new reshaped instance of the array.

In [118]:
r = np.arange(16)
print('original r: \n',r)
print('\nreshaped array: \n',r.reshape((4,4)))
print('\narray r after reshape was applied: \n',r)

original r: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

array r after reshape was applied: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [119]:
r = np.arange(16)
 
print('original r: \n',r)
print('\nresized array: \n',r.resize((4,4)))
print('\narray r after resize was applied: \n',r)

original r: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

resized array: 
 None

array r after resize was applied: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
